name: Unity Build And Test
on:
  schedule:
    - cron: '0 0 * * 0' # Every Sunday at midnight
  push:
    branches: [main]
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    branches: ['**']
  workflow_dispatch: # manual workflow trigger
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{(github.event_name == 'pull_request' || github.event.action == 'synchronize')}}
jobs:
  build-and-test:
    if: github.event.pull_request.draft == false
    permissions:
      contents: read
      actions: write
    secrets: inherit
    uses: RageAgainstThePixel/workflows/.github/workflows/run-build-and-test-unity-package.yml@dev
    with:
      build-options: ./.github/workflows/build-options.json
      group-by: unity-version
      job-name-prefix: Build and Test
